name: “My CI Workflow"
on:
 push:
 pull_request:
jobs:
 hello:
    runs-on: ubuntu-latest
    steps:
     - name: Print Hello
       run: echo Hello
 world:
   runs-on: windows-2022
   needs: hello
   steps:
     - name: Print World
       run: echo World!
